[package]
name = "rinput"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
atty = { version = "0.2",  optional = true }
termcolor   = { version = "1.1", optional = true }
yaml-rust   = { version = "0.4.1",  optional = true }
libc = "0.2"
gapbuffer = "0.1.1"
unicode-width = "0.1.1"
lazy_static = "0.2"
regex = "0.1"
tempdir = "0.3.0"

# rustbox
bitflags = "0.2.1"
termbox-sys = "0.2.9"
gag = "0.1.6"
num-traits = "0.1.13"

[lib]
name = "rinput"
path = "src/rinput/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rinput"
doc = false
