[package]
name = "rinput"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
atty = { version = "0.2",  optional = true }
termcolor   = { version = "1.1", optional = true }
yaml-rust   = { version = "0.4.1",  optional = true }
orbtk = { git = "https://github.com/redox-os/orbtk.git", branch = "develop" }
libc = "0.2"
gapbuffer = "0.1.1"
unicode-width = "0.1.1"
lazy_static = "0.2"

[dependencies.rustbox]
git = "https://github.com/gchp/rustbox"


[lib]
name = "rinput"
path = "src/rinput/lib.rs"


[[bin]]
path = "src/main.rs"
name = "rinput"
doc = false
