[package]
name = "rinput"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
atty = { version = "0.2",  optional = true }
termcolor   = { version = "1.1", optional = true }
yaml-rust   = { version = "0.4.1",  optional = true }
orbtk = { git = "https://github.com/redox-os/orbtk.git", branch = "develop" }
rustbox = "*"
libc = "0.2"

[features]
default     = []
std         = [] # support for no_std in a backwards-compatible way
yaml        = ["yaml-rust"]
cargo       = [] # Disable if you're not using Cargo, enables Cargo-env-var-dependent macros
unstable    = [] # for building with unstable clap features (doesn't require nightly Rust) (currently none)
debug       = [] # Enables debug messages
doc         = ["yaml"] # All the features which add to documentation
